[version]
current = "0.5.0b0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<pre>(a|b)\d+)?
'''

[git]
message_template = ":bookmark: Bump to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "setup.cfg"
version_template = "{major}.{minor}.{patch}{pre}"

[[file]]
src = "cookie_consent/__init__.py"
version_template = "{major}.{minor}.{patch}{pre}"

[[field]]
name = "pre"
default = ""
