name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build-js:
    runs-on: ubuntu-latest
    name: Compile the frontend code

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'js/.nvmrc'
          cache: npm

      - name: Build TS
        run: |
          npm ci
          npm run build
          npm run build:django-static
        working-directory: js

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
        django: ['3.2', '4.2', '5.0']
        exclude:
          - python: '3.11'
            django: '3.2'
          - python: '3.12'
            django: '3.2'
          - python: '3.8'
            django: '5.0'
          - python: '3.9'
            django: '5.0'

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          DJANGO: ${{ matrix.django }}

      - name: Publish coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: reports/

  e2e_tests:
    runs-on: ubuntu-latest
    name: Run the end-to-end tests

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install tox tox-gh-actions pytest-playwright
          playwright install --with-deps

      - name: Run tests
        run: tox -e e2e

      - name: Publish coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: reports/
