name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
        django: ['4.2', '5.0']
        include:
          - python: '3.8'
            django: '4.2'
          - python: '3.9'
            django: '4.2'

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }})

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          DJANGO: ${{ matrix.django }}

      - name: Publish coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: reports/

  e2e_tests:
    runs-on: ubuntu-latest
    name: Run the end-to-end tests

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install tox tox-gh-actions pytest-playwright
          playwright install --with-deps

      - name: Run tests
        run: tox -e e2e

      - name: Publish coverage report
        uses: codecov/codecov-action@v3
        with:
          directory: reports/
